### DISCUSSION TITLE
Whats the best approach for multiple mongodb ReplicaSets on a cluster?

### DISCUSSION THREAD

**Discussion by TheDukeDK** [maxisam/mgob#158] [Q&A]
I had intended to install mgob on my k8s cluster and then add backup-config files to a **central** `configMap` whenever I added a mongodb replicaSet. We will have several mongodb replicaSets managed by the MongoDB Community Operator running a K8s cluster. 

But it seems to require that we have at least one **Backup Plan**. This makes me wonder what the proper approach is...

One mgob per mongodb replicaSet? 

Or can we have one mgob to handle all of our mongodb replicaSets on a cluster?

- One mongob to be installed in it's own namespace. 
- Whenever we add a mongodb resource we would update the central configMap with a new entry.

```
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    role: mongo-backup
  name: mgob-config
  namespace: db
data:
  ##### Add and entry to this configmap for each mongodb we have #####
  mongodb-a.yml: |
    target:
      host: "mongodb-a-svc.namespace.svc.cluster.local,mongodb-a-0.mongodb-gb-svc.namespace.svc.cluster.local,mongodb-a-1.mongodb-gb-svc.namespace.svc.cluster.local,mongodb-a-2.mongodb-gb-svc.namespace.svc.cluster.local"
      port: 27017
      database: "admin"
    scheduler:
      cron: "*/1 * * * *"
      retention: 5
      timeout: 60
    retry:
      attempts: 3
      backoffFactor: 60
    s3:
      url: "https://api.minio.example.com"
      bucket: mongodb-a
      accessKey: "some-access-key"
      secretKey: "some-secret-key"
      api: "S3v4"
  mongodb-b.yml: |
    target:
      host: "mongodb-b-svc.namespace.svc.cluster.local,mongodb-b-0.mongodb-gb-svc.namespace.svc.cluster.local,mongodb-b-1.mongodb-gb-svc.namespace.svc.cluster.local,mongodb-b-2.mongodb-gb-svc.namespace.svc.cluster.local"
      port: 27017
      database: "admin"
    scheduler:
      cron: "*/1 * * * *"
      retention: 5
      timeout: 60
    retry:
      attempts: 3
      backoffFactor: 60
    s3:
      url: "https://api.minio.example.com"
      bucket: mongodb-b
      accessKey: "some-access-key"
      secretKey: "some-secret-key"
      api: "S3v4"
```
