### ISSUE TITLE
Removing the VOLUME instruction for the four mount points?

### ISSUE THREAD

**Issue by sjiep** [maxisam/mgob#125]
The `Dockerfile` defines a VOLUME instruction for the four mount points:

https://github.com/maxisam/mgob/blob/e405a578bbc58d4f22f4747d43e1944994166e58/Dockerfile#L58

Is there any specific reason why they are defined as a VOLUME? The host binded-mounts will still work without this declaration, however if one doesn't define these host binded-mounts then anonymous volumes are created instead.

The latter results in odd behaviour when building a new image with mgob as the base image and copying config files into the base image, .e.g.

```dockerfile
# Dockerfile
FROM maxisam/mgob:2.0.22-rclone

COPY ./gpg /gpg
COPY ./config/plan.yml /config/plan.yml
```

```yaml
# compose.yml
services: 
  mgob:
    build:
      context: ./mgob
    environment:
      PLAN__TARGET_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:?required}"
    volumes:
      - "./mgob/storage:/storage"
```

The odd behaviour being that changing values in the `plan.yml` followed by a rebuild of the image via `docker compose up --build -d` will trigger a new image to be built, however the restarted container still has the old config values as an anonymous volume is being used.

Removing the VOLUME instruction should get rid of this odd behaviour without any downsides (as far as I can tell). 

Can I make PR for this?
