### ISSUE TITLE
Enhance Contribution Experience by Utilizing Environment Variables in GitHub Workflows

### ISSUE THREAD

**Issue by danielchristianschroeter** [maxisam/mgob#144]
Current GitHub workflows in the `mgob` repository contain several hardcoded values, which make it challenging for contributors to test changes in their own forks without manual modifications. This proposal suggests leveraging GitHub Environments to manage these variables, provide default values for ease of use in forks, and improve the overall contribution experience.

### Problems Identified:
1. **Hardcoded Values**: Workflows contain hardcoded Docker repository names and version tags, such as:
    - `tags: maxisam/mongo-tool:${{ env.VERSION }}`
    - `tags: ${{ github.repository }}:${{ env.APP_VERSION }}.${{ github.run_number }}`
    - `repository: maxisam/mgob`
    - `bucket: "maxisam-mgob"`

2. **Lack of Flexibility for Forks**: Contributors must manually edit workflow files to replace repository names with their own Docker Hub accounts.

3. **Reduced Testing Capability**: Forks lack access to the original repository's GitHub secrets and environment variables, causing issues if the exact setup isn't replicated.

### Proposed Solution:
1. **Utilize GitHub Environments**:
   - Define environment variables like `DOCKER_REPOSITORY` at the repository level.
   - These variables can be accessed in workflows using `${{ vars.VAR_NAME }}`.

2. **Provide Default Values in Workflows**:
   - Set defaults directly within workflows to aid contributors working in forks.
   - Example:
     ```yaml
     env:
       APP_VERSION: ${{ vars.APP_VERSION || 'dev' }}
       DOCKER_REPOSITORY: ${{ vars.DOCKER_REPOSITORY || github.repository_owner }}
     ```

3. **Document Setup for Contributors**:
   - Update repository documentation to include instructions for setting environment variables locally or in forks.
   - Example of how to define these variables in a workflow:
     ```yaml
     on:
       workflow_dispatch:
         inputs:
           docker_repository:
             description: 'Docker Hub repository name'
             required: true
           version:
             description: 'Version of the build'
             default: 'latest'
     ```

4. **Ensure Testing Completeness**:
   - Split workflows into testing and deployment stages to allow contributors to test functionality without pushing to Docker Hub inadvertently.
   - Example block for Docker tagging using environment:
     ```yaml
     with:
       tags: ${{ env.DOCKER_REPOSITORY }}/mgob:${{ env.APP_VERSION }}.${{ github.run_number }}
     ```

See also https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables
### Benefit:
- **Improved Contribution Experience**: Eases the testing process in forks leading to more efficient development and contributions.
- **Consistency Across Development Environments**: Establishes a standard approach to using variables, making the setup process uniform and less error-prone.

Addressing these items will streamline the workflow for both maintainers and contributors, fostering an open and collaborative environment. Please consider this enhancement to improve the contribution process.
