### ISSUE TITLE
Metrics page doesn't return any information about the actual backups

### ISSUE THREAD

**Issue by botiapa** [maxisam/mgob#46]
The `/metrics` page only returns data about the go instance and promhttp, but does not return any about the actual backups themselves. Meaning `mgob_scheduler_backup_total`, or `mgob_scheduler_backup_latency` and others are missing. I'm running it in a docker instance using the latest version. Here's the version info:

`{"arch":"amd64","cpu_count":"16","go_version":"go1.19.3","goroutines":"7","max_procs":"16","mgob_version":"1.9.13","os":"linux","repository":"github.com/maxisam/mgob"}`

Any help is appreciated.

**Comment by maxisam** [comment]
I am not sure how to help. It works on my end.


```
# HELP mgob_scheduler_backup_latency Backup duration in seconds.
# TYPE mgob_scheduler_backup_latency summary
mgob_scheduler_backup_latency_sum{plan="cms-content-dev",status="200"} 15917.958965702997
mgob_scheduler_backup_latency_count{plan="cms-content-dev",status="200"} 567
mgob_scheduler_backup_latency_sum{plan="cms-content-dev",status="500"} 371.061660803
mgob_scheduler_backup_latency_count{plan="cms-content-dev",status="500"} 2
mgob_scheduler_backup_latency_sum{plan="cms-content-prod",status="200"} 2552.2881024550006
mgob_scheduler_backup_latency_count{plan="cms-content-prod",status="200"} 566
mgob_scheduler_backup_latency_sum{plan="cms-content-prod",status="500"} 349.073132629
mgob_scheduler_backup_latency_count{plan="cms-content-prod",status="500"} 2
mgob_scheduler_backup_latency_sum{plan="cms-dev",status="200"} 78635.81559780604
mgob_scheduler_backup_latency_count{plan="cms-dev",status="200"} 93
mgob_scheduler_backup_latency_sum{plan="cms-dev",status="500"} 1608.2934267619999
mgob_scheduler_backup_latency_count{plan="cms-dev",status="500"} 2
mgob_scheduler_backup_latency_sum{plan="cms-prod",status="200"} 9700.287350964001
mgob_scheduler_backup_latency_count{plan="cms-prod",status="200"} 95


# HELP mgob_scheduler_backup_total The total number of backups.
# TYPE mgob_scheduler_backup_total counter
mgob_scheduler_backup_total{plan="cms-content-dev",status="200"} 567
mgob_scheduler_backup_total{plan="cms-content-dev",status="500"} 2
mgob_scheduler_backup_total{plan="cms-content-prod",status="200"} 566
mgob_scheduler_backup_total{plan="cms-content-prod",status="500"} 2
mgob_scheduler_backup_total{plan="cms-dev",status="200"} 93
mgob_scheduler_backup_total{plan="cms-dev",status="500"} 2
mgob_scheduler_backup_total{plan="cms-prod",status="200"} 95
```

**Comment by maxisam** [comment]
Maybe you can provide your settings?

**Comment by botiapa** [comment]
Sure, here's my config:
```
scheduler:
    # run every day at 3 am (careful: UTC)
    cron: "0 1 * * *"
    # number of backups to keep locally
    retention: 14
    # backup operation timeout in minutes
    timeout: 60
target:
    # mongod IP or host name
    host: "mongo"
    # mongodb port
    port: 27017
    # mongodb database name, leave blank to backup all databases
    database: "maindatabase"
    # leave blank if auth is not enabled
    username: "somethingusername"
    password: "securepassword"
# Encryption (optional)
encryption:
    gpg:
        recipients:
            - "test@emailadress.com"
```
