### ISSUE TITLE
Office365 mail auth error

### ISSUE THREAD

**Issue by blueiceprj** [maxisam/mgob#52]
Office365 login error

`time="2023-03-23T18:00:44Z" level=error msg="Notifier failed sending email notification failed: 504 5.7.4 Unrecognized authentication type [FR2P281CA0035.DEUP281.PROD.OUTLOOK.COM 2023-03-23T18:00:39.250Z 08DB2B43918359DA]" plan=xxxxxxxxxxxxx
`

```
smtp:
  server: smtp.office365.com
  port: 587
  username: no-reply@xxxxxx
  password: yyyyyyyyyy
  from: no-reply@xxxxxx
  to:
    - xxxxx@gmail.com
    - xxxxxxxxx@gmail.com
```
