### ISSUE TITLE
error ls: *.gz.encrypted: No such file or directory

### ISSUE THREAD

**Issue by jamesholcomb** [maxisam/mgob#55]
mgob-config

```yaml
target:
  host: "db-mongodb.default.svc.cluster.local"
  port: 27017
  # add custom params to mongodump (eg. Auth or SSL support), leave blank if not needed
  params: ""
scheduler:
  # Daily at 5am UCT https://crontab.guru/#0_5_*_*_*
  cron: "0 5 */1 * *"
  retention: 1
  timeout: 60
gcloud:
  bucket: "myapp-test_mongodbdump"
  keyFilePath: /etc/mgob/service-account.json
slack:
  url: [redacted]
  channel: myapp-devops
  username: mgob
  # 'true' to notify only on failures 
  warnOnly: true
```

```sh
time="2023-03-25T19:11:20Z" level=info msg="new dump" archive=/tmp/myapp-test-1679771441.gz err="<nil>" mlog=/tmp/myapp-test-1679771441.log
ls: *.gz.encrypted: No such file or directory
time="2023-03-25T19:11:22Z" level=info msg="Local backup finished Local backup finished `/tmp/myapp-test-1679771441.gz` -> `/storage/myapp-test/myapp-test-1679771441.gz` Duration: 1.723790023s" plan=myapp-test
```

Cloned and built using https://github.com/maxisam/mgob/tree/366207a0954fbfdf684cf0726c8b14e71f94ee08

I verified that the gz backup file and log file were created in `/storage/myapp-test`

I am migrating from stefanprodan on GCP k8s...please let me know if any other repro steps are necessary.
