### ISSUE TITLE
add restore support as alternate mode

### ISSUE THREAD

**Issue by scicco** [maxisam/mgob#59]
Hello @maxisam,

first of all, thank you for your work on this project.

Currently, inside readme, the "Restore" paragraph states that you have to exec inside a running container the mongorestore command with the needed parameters.

It would be nice to support some switch to indicate that we actually want to start the container and restore an existent backup inside /storage/ and then exit the container.

# Example

inside the configuration file if an `archive` option exists this option will override the default behaviour and run mongorestore command.

mongorestore.yaml file

```
scheduler:
  cron: "0 3 * * *"
  retention: 14
  timeout: 60
archive: "/storage/last_mongodb_backup.gz"
target:
  host: "mongodb"
  port: 27017
  database: ""
  username: "root"
  password: "mySecretPassw0rd"
  params: "--authenticationDatabase admin --ssl --sslCAFile=/certs/mongodb/mongodb-ca.pem --sslPEMKeyFile=/certs/mongodb/mongodb-client.pem --sslAllowInvalidCertificates"
```

This configuration file allows mongorestore to use the following parameters:

- archive
- target.host
- target.port
- target.database (that is actually skipped because it's empty)
- target.username
- target.password
- target.params

and will be equivalent to connecting to a running container and running the following command:

```
mongorestore \
--host=mongodb \
-u root --password=mySecretPassw0rd --authenticationDatabase admin \
--ssl --sslCAFile=/certs/mongodb/mongodb-ca.pem --sslPEMKeyFile=/certs/mongodb/mongodb-client.pem --sslAllowInvalidCertificates \
--gzip --archive=/storage/last_backup.gz
```

Here it is the docker-compose.yml relevant part for the example

```
...
  mongorestore:
    hostname: mongorestore
    image: maxisam/mgob:1.10.14-all
    volumes:
      - ./mongodb_backup:/tmp
      - ./mongodb_backup:/data
      - ./mongodb_backup/mongorestore.yaml:/config/mongorestore.yaml:ro
      - ./certs:/certs:ro
      - ./mongodb_backup/backup:/storage
    environment:
      - -LogLevel=info
...
```

Maybe adding support for connection string as an option for restore could be also very useful and simplify it.

Thank you in advance
