### ISSUE TITLE
Error sending notification email

### ISSUE THREAD

**Issue by joeldatabox** [maxisam/mgob#62]
I have a problem with sending notifications. Right after running the backup I always come across the following error below:

`mgob-backup-manager  | time="2023-06-09T07:23:53Z" level=info msg="Backup finished in 4h23m53.110717758s archive mydatabase-1686279600.gz size 2.1 GB" plan=mydatabase
mgob-backup-manager  | time="2023-06-09T07:28:13Z" level=error msg="Notifier failed sending email notification failed: dial tcp 191.6.216.100:587: connect: connection timed out" plan=mydatabase
mgob-backup-manager  | time="2023-06-09T07:28:13Z" level=info msg="Next run at 2023-06-10 03:00:00 +0000 UTC" plan=mydatabase
`

Detail: Before making the settings for production, I created an example for validation and testing. During the tests the database had almost no data and right after the backup I always received the email smoothly.

What could be happening?

**Comment by woraccmsq** [comment]
I also have an issue with e-mail sending: 
`time="2023-06-14T01:00:41Z" level=error msg="Notifier failed sending email notification failed: x509: certificate signed by unknown authority"`

**Comment by maxisam** [comment]
@joeldatabox it seems like it has an issue on connection

Notifier failed sending email notification failed: dial tcp 191.6.216.100:587: connect: connection timed out.

Do you have the same setup for testing and production?

**Comment by maxisam** [comment]
@woraccmsq for your smtp settings

```yml
      smtp:
        server: xxx
        warnOnly: true
        insecureSkipVerify: true # <-- this is the setting for your issue
        tlsEnabled: true
        port: 25
```
