### ISSUE TITLE
Configure target with connection string URI

### ISSUE THREAD

**Issue by hypesystem** [maxisam/mgob#81]
In the examples in the README for how to configure a target mongod the format is something like this:

```yaml
target:
  # mongod IP or host name
  host: "172.18.7.21"
  # mongodb port
  port: 27017
  # mongodb database name, leave blank to backup all databases
  database: "test"
  # leave blank if auth is not enabled
  username: "admin"
  password: "secret"
```

The kubernetes MongoCommunity operator automatically creates secrets with a [connection string](https://www.mongodb.com/docs/manual/reference/connection-string/), which means it would be nice to be able to set that directly in the config:

```yaml
target:
  connectionString: mongodb://admin:secret@172.18.7.21/test
```

See the mongodb community operator docs here: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md#deploy-a-replica-set

Is this something that could be considered as an additional option?
