### ISSUE TITLE
Environment variables injection

### ISSUE THREAD

**Issue by ngsandbox** [maxisam/mgob#93]
Hi, 
would it be possible to inject environment variables to config-files via Kubernetes configuration?

As an example, Kubernetes StatefulSet with attached secret-password from `mongodb-backup-creds`:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-backup
  namespace: mongodb
spec:
  serviceName: "mgob"
  replicas: 1
  template:
    spec:
      containers:
        - name: mongodb-backup
          image: maxisam/mgob:2.0.18-all
          env:
            - name: BACKUP_PWD
              valueFrom:
                secretKeyRef:
                  name: mongodb-backup-creds
                  key: password
```

Kubernetes config-map with `BACKUP_PWD` injection:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: mongodb-backup
  namespace: mongodb
data:
  mongodb-backup.yml: |
    target:
      host: "mongodb-0.mongodb,mongodb-1.mongodb,mongodb-2.mongodb"
      port: 27017
      username: "backup"
      password: "$BACKUP_PWD"
    scheduler:
      cron: "0 2 * * *"
      retention: 14
      timeout: 60
```
